name: Context testing
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#startswith
on: [push,pull_request]
# contains 检查第二个参数中的字符串是否包含在第一个参数中的字符串中
# startsWith 检查一个字符串是否以另一个字符串开头
jobs:
  functions:
    # 这里不能使用 ubuntu-16.04 使用了运行不了
    runs-on: ubuntu-latest  
    steps: 
      - name: dump
        run: |
          echo ${{ contains( 'hello','ll')}}
          echo ${{ startsWith( 'hello','he')}}
          echo ${{ endsWith('hello','lo')}}
          echo ${{ format('hello {0} {1} {2}','word','!','!')}}
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    # 只会在推送时运行以下的程序
    if: github.event_name == 'pull'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}  # 使用toJson函数
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        # failure 只会在上一步失败时返回 true 
        if: failure()
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
